// FIELDS
export const INIT_FIELD = 'INIT_FIELD'
export const UPDATE_FIELD = 'UPDATE_FIELD'
export const ERROR_FIELD = 'ERROR_FIELD'
export const DELETE_FIELD = 'DELETE_FIELD'
// FORMS
export const SUBMIT_FORM = 'SUBMIT_FORM'
// TRANSIENTS
export const INIT_TRANSIENT = 'INIT_TRANSIENT'
export const TOGGLE_TRANSIENT = 'TOGGLE_TRANSIENT'
